### ISSUE TITLE
how to change the input

### ISSUE THREAD

**Issue by mmmmayi** [aivclab/vision#1]
I have two inputs for my model, could you please tell me how to change the input in follow code? 
`  W = {model.graph.input[0].name:x.data.numpy()}
  c2_out = prepared_backend.run(W)[0]`
Thanks for your attention

**Comment by cnheider** [comment]
You would do W = {model.graph.input[0].name: x.data.numpy(), model.graph.input[1].name: y.data.numpy()}

But note caffe2 has been deprecated so expected better solutions to appear soon, read more here: https://caffe2.ai/blog/2018/05/02/Caffe2_PyTorch_1_0.html
